server:
  port: 8080
spring:
  application:
    name: "crud demo"
  datasource:
    url: jdbc:mysql://localhost:3306/employee_directory
    username: springstudent
    password: springstudent
  jpa:
    show-sql: true